# Generated by Django 4.1.7 on 2023-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalpath',
            name='heading',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
